//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookCilent.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string authorField;
        
        private double priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string publicsherField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string author {
            get {
                return this.authorField;
            }
            set {
                if ((object.ReferenceEquals(this.authorField, value) != true)) {
                    this.authorField = value;
                    this.RaisePropertyChanged("author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string publicsher {
            get {
                return this.publicsherField;
            }
            set {
                if ((object.ReferenceEquals(this.publicsherField, value) != true)) {
                    this.publicsherField = value;
                    this.RaisePropertyChanged("publicsher");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.BookServiceSoap")]
    public interface BookServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        BookCilent.ServiceReference1.HelloWorldResponse HelloWorld(BookCilent.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<BookCilent.ServiceReference1.HelloWorldResponse> HelloWorldAsync(BookCilent.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/themSach", ReplyAction="*")]
        BookCilent.ServiceReference1.themSachResponse themSach(BookCilent.ServiceReference1.themSachRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/themSach", ReplyAction="*")]
        System.Threading.Tasks.Task<BookCilent.ServiceReference1.themSachResponse> themSachAsync(BookCilent.ServiceReference1.themSachRequest request);
        
        // CODEGEN: Generating message contract since element name dsSachResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dsSach", ReplyAction="*")]
        BookCilent.ServiceReference1.dsSachResponse dsSach(BookCilent.ServiceReference1.dsSachRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dsSach", ReplyAction="*")]
        System.Threading.Tasks.Task<BookCilent.ServiceReference1.dsSachResponse> dsSachAsync(BookCilent.ServiceReference1.dsSachRequest request);
        
        // CODEGEN: Generating message contract since element name timKiemTheoIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/timKiemTheoId", ReplyAction="*")]
        BookCilent.ServiceReference1.timKiemTheoIdResponse timKiemTheoId(BookCilent.ServiceReference1.timKiemTheoIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/timKiemTheoId", ReplyAction="*")]
        System.Threading.Tasks.Task<BookCilent.ServiceReference1.timKiemTheoIdResponse> timKiemTheoIdAsync(BookCilent.ServiceReference1.timKiemTheoIdRequest request);
        
        // CODEGEN: Generating message contract since element name author from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/timKiemTheoAuThor", ReplyAction="*")]
        BookCilent.ServiceReference1.timKiemTheoAuThorResponse timKiemTheoAuThor(BookCilent.ServiceReference1.timKiemTheoAuThorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/timKiemTheoAuThor", ReplyAction="*")]
        System.Threading.Tasks.Task<BookCilent.ServiceReference1.timKiemTheoAuThorResponse> timKiemTheoAuThorAsync(BookCilent.ServiceReference1.timKiemTheoAuThorRequest request);
        
        // CODEGEN: Generating message contract since element name publicsher from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/timKiemTheoPublicsher", ReplyAction="*")]
        BookCilent.ServiceReference1.timKiemTheoPublicsherResponse timKiemTheoPublicsher(BookCilent.ServiceReference1.timKiemTheoPublicsherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/timKiemTheoPublicsher", ReplyAction="*")]
        System.Threading.Tasks.Task<BookCilent.ServiceReference1.timKiemTheoPublicsherResponse> timKiemTheoPublicsherAsync(BookCilent.ServiceReference1.timKiemTheoPublicsherRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public BookCilent.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(BookCilent.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookCilent.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(BookCilent.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class themSachRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="themSach", Namespace="http://tempuri.org/", Order=0)]
        public BookCilent.ServiceReference1.themSachRequestBody Body;
        
        public themSachRequest() {
        }
        
        public themSachRequest(BookCilent.ServiceReference1.themSachRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class themSachRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string author;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string puclicsher;
        
        public themSachRequestBody() {
        }
        
        public themSachRequestBody(long id, string title, string author, double price, string puclicsher) {
            this.id = id;
            this.title = title;
            this.author = author;
            this.price = price;
            this.puclicsher = puclicsher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class themSachResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="themSachResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookCilent.ServiceReference1.themSachResponseBody Body;
        
        public themSachResponse() {
        }
        
        public themSachResponse(BookCilent.ServiceReference1.themSachResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class themSachResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool themSachResult;
        
        public themSachResponseBody() {
        }
        
        public themSachResponseBody(bool themSachResult) {
            this.themSachResult = themSachResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dsSachRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dsSach", Namespace="http://tempuri.org/", Order=0)]
        public BookCilent.ServiceReference1.dsSachRequestBody Body;
        
        public dsSachRequest() {
        }
        
        public dsSachRequest(BookCilent.ServiceReference1.dsSachRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class dsSachRequestBody {
        
        public dsSachRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class dsSachResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="dsSachResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookCilent.ServiceReference1.dsSachResponseBody Body;
        
        public dsSachResponse() {
        }
        
        public dsSachResponse(BookCilent.ServiceReference1.dsSachResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class dsSachResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookCilent.ServiceReference1.Book[] dsSachResult;
        
        public dsSachResponseBody() {
        }
        
        public dsSachResponseBody(BookCilent.ServiceReference1.Book[] dsSachResult) {
            this.dsSachResult = dsSachResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class timKiemTheoIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="timKiemTheoId", Namespace="http://tempuri.org/", Order=0)]
        public BookCilent.ServiceReference1.timKiemTheoIdRequestBody Body;
        
        public timKiemTheoIdRequest() {
        }
        
        public timKiemTheoIdRequest(BookCilent.ServiceReference1.timKiemTheoIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class timKiemTheoIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public timKiemTheoIdRequestBody() {
        }
        
        public timKiemTheoIdRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class timKiemTheoIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="timKiemTheoIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookCilent.ServiceReference1.timKiemTheoIdResponseBody Body;
        
        public timKiemTheoIdResponse() {
        }
        
        public timKiemTheoIdResponse(BookCilent.ServiceReference1.timKiemTheoIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class timKiemTheoIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookCilent.ServiceReference1.Book timKiemTheoIdResult;
        
        public timKiemTheoIdResponseBody() {
        }
        
        public timKiemTheoIdResponseBody(BookCilent.ServiceReference1.Book timKiemTheoIdResult) {
            this.timKiemTheoIdResult = timKiemTheoIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class timKiemTheoAuThorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="timKiemTheoAuThor", Namespace="http://tempuri.org/", Order=0)]
        public BookCilent.ServiceReference1.timKiemTheoAuThorRequestBody Body;
        
        public timKiemTheoAuThorRequest() {
        }
        
        public timKiemTheoAuThorRequest(BookCilent.ServiceReference1.timKiemTheoAuThorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class timKiemTheoAuThorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string author;
        
        public timKiemTheoAuThorRequestBody() {
        }
        
        public timKiemTheoAuThorRequestBody(string author) {
            this.author = author;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class timKiemTheoAuThorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="timKiemTheoAuThorResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookCilent.ServiceReference1.timKiemTheoAuThorResponseBody Body;
        
        public timKiemTheoAuThorResponse() {
        }
        
        public timKiemTheoAuThorResponse(BookCilent.ServiceReference1.timKiemTheoAuThorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class timKiemTheoAuThorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookCilent.ServiceReference1.Book[] timKiemTheoAuThorResult;
        
        public timKiemTheoAuThorResponseBody() {
        }
        
        public timKiemTheoAuThorResponseBody(BookCilent.ServiceReference1.Book[] timKiemTheoAuThorResult) {
            this.timKiemTheoAuThorResult = timKiemTheoAuThorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class timKiemTheoPublicsherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="timKiemTheoPublicsher", Namespace="http://tempuri.org/", Order=0)]
        public BookCilent.ServiceReference1.timKiemTheoPublicsherRequestBody Body;
        
        public timKiemTheoPublicsherRequest() {
        }
        
        public timKiemTheoPublicsherRequest(BookCilent.ServiceReference1.timKiemTheoPublicsherRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class timKiemTheoPublicsherRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string publicsher;
        
        public timKiemTheoPublicsherRequestBody() {
        }
        
        public timKiemTheoPublicsherRequestBody(string publicsher) {
            this.publicsher = publicsher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class timKiemTheoPublicsherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="timKiemTheoPublicsherResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookCilent.ServiceReference1.timKiemTheoPublicsherResponseBody Body;
        
        public timKiemTheoPublicsherResponse() {
        }
        
        public timKiemTheoPublicsherResponse(BookCilent.ServiceReference1.timKiemTheoPublicsherResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class timKiemTheoPublicsherResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookCilent.ServiceReference1.Book[] timKiemTheoPublicsherResult;
        
        public timKiemTheoPublicsherResponseBody() {
        }
        
        public timKiemTheoPublicsherResponseBody(BookCilent.ServiceReference1.Book[] timKiemTheoPublicsherResult) {
            this.timKiemTheoPublicsherResult = timKiemTheoPublicsherResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BookServiceSoapChannel : BookCilent.ServiceReference1.BookServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookServiceSoapClient : System.ServiceModel.ClientBase<BookCilent.ServiceReference1.BookServiceSoap>, BookCilent.ServiceReference1.BookServiceSoap {
        
        public BookServiceSoapClient() {
        }
        
        public BookServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookCilent.ServiceReference1.HelloWorldResponse BookCilent.ServiceReference1.BookServiceSoap.HelloWorld(BookCilent.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            BookCilent.ServiceReference1.HelloWorldRequest inValue = new BookCilent.ServiceReference1.HelloWorldRequest();
            inValue.Body = new BookCilent.ServiceReference1.HelloWorldRequestBody();
            BookCilent.ServiceReference1.HelloWorldResponse retVal = ((BookCilent.ServiceReference1.BookServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookCilent.ServiceReference1.HelloWorldResponse> BookCilent.ServiceReference1.BookServiceSoap.HelloWorldAsync(BookCilent.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookCilent.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            BookCilent.ServiceReference1.HelloWorldRequest inValue = new BookCilent.ServiceReference1.HelloWorldRequest();
            inValue.Body = new BookCilent.ServiceReference1.HelloWorldRequestBody();
            return ((BookCilent.ServiceReference1.BookServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookCilent.ServiceReference1.themSachResponse BookCilent.ServiceReference1.BookServiceSoap.themSach(BookCilent.ServiceReference1.themSachRequest request) {
            return base.Channel.themSach(request);
        }
        
        public bool themSach(long id, string title, string author, double price, string puclicsher) {
            BookCilent.ServiceReference1.themSachRequest inValue = new BookCilent.ServiceReference1.themSachRequest();
            inValue.Body = new BookCilent.ServiceReference1.themSachRequestBody();
            inValue.Body.id = id;
            inValue.Body.title = title;
            inValue.Body.author = author;
            inValue.Body.price = price;
            inValue.Body.puclicsher = puclicsher;
            BookCilent.ServiceReference1.themSachResponse retVal = ((BookCilent.ServiceReference1.BookServiceSoap)(this)).themSach(inValue);
            return retVal.Body.themSachResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookCilent.ServiceReference1.themSachResponse> BookCilent.ServiceReference1.BookServiceSoap.themSachAsync(BookCilent.ServiceReference1.themSachRequest request) {
            return base.Channel.themSachAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookCilent.ServiceReference1.themSachResponse> themSachAsync(long id, string title, string author, double price, string puclicsher) {
            BookCilent.ServiceReference1.themSachRequest inValue = new BookCilent.ServiceReference1.themSachRequest();
            inValue.Body = new BookCilent.ServiceReference1.themSachRequestBody();
            inValue.Body.id = id;
            inValue.Body.title = title;
            inValue.Body.author = author;
            inValue.Body.price = price;
            inValue.Body.puclicsher = puclicsher;
            return ((BookCilent.ServiceReference1.BookServiceSoap)(this)).themSachAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookCilent.ServiceReference1.dsSachResponse BookCilent.ServiceReference1.BookServiceSoap.dsSach(BookCilent.ServiceReference1.dsSachRequest request) {
            return base.Channel.dsSach(request);
        }
        
        public BookCilent.ServiceReference1.Book[] dsSach() {
            BookCilent.ServiceReference1.dsSachRequest inValue = new BookCilent.ServiceReference1.dsSachRequest();
            inValue.Body = new BookCilent.ServiceReference1.dsSachRequestBody();
            BookCilent.ServiceReference1.dsSachResponse retVal = ((BookCilent.ServiceReference1.BookServiceSoap)(this)).dsSach(inValue);
            return retVal.Body.dsSachResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookCilent.ServiceReference1.dsSachResponse> BookCilent.ServiceReference1.BookServiceSoap.dsSachAsync(BookCilent.ServiceReference1.dsSachRequest request) {
            return base.Channel.dsSachAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookCilent.ServiceReference1.dsSachResponse> dsSachAsync() {
            BookCilent.ServiceReference1.dsSachRequest inValue = new BookCilent.ServiceReference1.dsSachRequest();
            inValue.Body = new BookCilent.ServiceReference1.dsSachRequestBody();
            return ((BookCilent.ServiceReference1.BookServiceSoap)(this)).dsSachAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookCilent.ServiceReference1.timKiemTheoIdResponse BookCilent.ServiceReference1.BookServiceSoap.timKiemTheoId(BookCilent.ServiceReference1.timKiemTheoIdRequest request) {
            return base.Channel.timKiemTheoId(request);
        }
        
        public BookCilent.ServiceReference1.Book timKiemTheoId(long id) {
            BookCilent.ServiceReference1.timKiemTheoIdRequest inValue = new BookCilent.ServiceReference1.timKiemTheoIdRequest();
            inValue.Body = new BookCilent.ServiceReference1.timKiemTheoIdRequestBody();
            inValue.Body.id = id;
            BookCilent.ServiceReference1.timKiemTheoIdResponse retVal = ((BookCilent.ServiceReference1.BookServiceSoap)(this)).timKiemTheoId(inValue);
            return retVal.Body.timKiemTheoIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookCilent.ServiceReference1.timKiemTheoIdResponse> BookCilent.ServiceReference1.BookServiceSoap.timKiemTheoIdAsync(BookCilent.ServiceReference1.timKiemTheoIdRequest request) {
            return base.Channel.timKiemTheoIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookCilent.ServiceReference1.timKiemTheoIdResponse> timKiemTheoIdAsync(long id) {
            BookCilent.ServiceReference1.timKiemTheoIdRequest inValue = new BookCilent.ServiceReference1.timKiemTheoIdRequest();
            inValue.Body = new BookCilent.ServiceReference1.timKiemTheoIdRequestBody();
            inValue.Body.id = id;
            return ((BookCilent.ServiceReference1.BookServiceSoap)(this)).timKiemTheoIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookCilent.ServiceReference1.timKiemTheoAuThorResponse BookCilent.ServiceReference1.BookServiceSoap.timKiemTheoAuThor(BookCilent.ServiceReference1.timKiemTheoAuThorRequest request) {
            return base.Channel.timKiemTheoAuThor(request);
        }
        
        public BookCilent.ServiceReference1.Book[] timKiemTheoAuThor(string author) {
            BookCilent.ServiceReference1.timKiemTheoAuThorRequest inValue = new BookCilent.ServiceReference1.timKiemTheoAuThorRequest();
            inValue.Body = new BookCilent.ServiceReference1.timKiemTheoAuThorRequestBody();
            inValue.Body.author = author;
            BookCilent.ServiceReference1.timKiemTheoAuThorResponse retVal = ((BookCilent.ServiceReference1.BookServiceSoap)(this)).timKiemTheoAuThor(inValue);
            return retVal.Body.timKiemTheoAuThorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookCilent.ServiceReference1.timKiemTheoAuThorResponse> BookCilent.ServiceReference1.BookServiceSoap.timKiemTheoAuThorAsync(BookCilent.ServiceReference1.timKiemTheoAuThorRequest request) {
            return base.Channel.timKiemTheoAuThorAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookCilent.ServiceReference1.timKiemTheoAuThorResponse> timKiemTheoAuThorAsync(string author) {
            BookCilent.ServiceReference1.timKiemTheoAuThorRequest inValue = new BookCilent.ServiceReference1.timKiemTheoAuThorRequest();
            inValue.Body = new BookCilent.ServiceReference1.timKiemTheoAuThorRequestBody();
            inValue.Body.author = author;
            return ((BookCilent.ServiceReference1.BookServiceSoap)(this)).timKiemTheoAuThorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookCilent.ServiceReference1.timKiemTheoPublicsherResponse BookCilent.ServiceReference1.BookServiceSoap.timKiemTheoPublicsher(BookCilent.ServiceReference1.timKiemTheoPublicsherRequest request) {
            return base.Channel.timKiemTheoPublicsher(request);
        }
        
        public BookCilent.ServiceReference1.Book[] timKiemTheoPublicsher(string publicsher) {
            BookCilent.ServiceReference1.timKiemTheoPublicsherRequest inValue = new BookCilent.ServiceReference1.timKiemTheoPublicsherRequest();
            inValue.Body = new BookCilent.ServiceReference1.timKiemTheoPublicsherRequestBody();
            inValue.Body.publicsher = publicsher;
            BookCilent.ServiceReference1.timKiemTheoPublicsherResponse retVal = ((BookCilent.ServiceReference1.BookServiceSoap)(this)).timKiemTheoPublicsher(inValue);
            return retVal.Body.timKiemTheoPublicsherResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookCilent.ServiceReference1.timKiemTheoPublicsherResponse> BookCilent.ServiceReference1.BookServiceSoap.timKiemTheoPublicsherAsync(BookCilent.ServiceReference1.timKiemTheoPublicsherRequest request) {
            return base.Channel.timKiemTheoPublicsherAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookCilent.ServiceReference1.timKiemTheoPublicsherResponse> timKiemTheoPublicsherAsync(string publicsher) {
            BookCilent.ServiceReference1.timKiemTheoPublicsherRequest inValue = new BookCilent.ServiceReference1.timKiemTheoPublicsherRequest();
            inValue.Body = new BookCilent.ServiceReference1.timKiemTheoPublicsherRequestBody();
            inValue.Body.publicsher = publicsher;
            return ((BookCilent.ServiceReference1.BookServiceSoap)(this)).timKiemTheoPublicsherAsync(inValue);
        }
    }
}
